---
output: html_document
---
Note that there are three column name types, that are *LastName*, *Name* and *Abbrev*. *Name* and *Abbrev* column types could have a number added to include more names and abbreviations for a given specialist. If a specialist name included in *LastName* or *Name* columns has accented or special characters, you should provide two lines for this specialist, one with and other without special characters, in order to accomodate the possible variations in names' writing (e.g. two variations of Ollgaard in the example table).In *Abbrev* column type provide abbreviations only for the names, not for the last name. Note, also, that since the specialists' names differ in length some cells are empty.

After upload the occurence and specialist's table click in the button **Go!** to  run the classification algorithm based on the six criteria presented previously. There will be situations in which the **naturaList** will not be confident regarding if the taxonomist who determined the species of an occurence is a specialist. In these cases, **naturaList** asks the user if the taxonomist's name really corresponds to a specialist. Then, the user should answer if the name correspond to a specialist's name. If the user ignore the manual verification, the occurence will be classified in a intermediate level, coded as `Level_1_verify`, which will be present in file with all classified occurrences. This levels is ignored in grid filter module, hence, will not be present in file with only grid filtered occurences. 

#### **Grid filter**

In this module **naturaList** performs the filter of occurences in grid cells with a size (in decimal degrees) specified by the user. In each grid cell **naturaList** mantains only the occurence with the highest level of confidence. This is an important step when the objective is focused on the use of occurence records to run species distribution models (SDM). In cases where a cell presents occurrences with the same level of confidence (for example, two points classified in Level 1) there are two tie-breaking criteria. The first is the determination date and the second is the collection date, both selecting the most recent record. If the tie persists, **naturaList** randomly choose one record (since both records present exactly the same degree of confidence). 

The process performed in Grid Filter module is illustrated in the following figure:





